name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and run tests
      run: |
        git submodule update --init --recursive
        git submodule update --remote
        cmake -B./lib/Catch2/build -H./lib/Catch2/ -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX=./catch_install
        cd lib/Catch2/build
        make install
        cd ../../..
        cmake -B./lib/fmt/build -H./lib/fmt -DFMT_TEST=OFF
        cd lib/fmt/build
        make -j8
        cd ../../..
        cmake -B./build -H. -Dfmt_DIR=./lib/fmt/build -DCatch2_DIR=./catch_install/lib/cmake/Catch2
        cd build
        make -j8
        make test
