name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Build and run tests
      run: |
        sudo add-apt-repository ppa:jonathonf/gcc-9.0
        sudo apt update
        sudo apt install -y gcc-9
        update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100 --slave /usr/bin/cc cc /usr/bin/gcc-9 --slave /usr/bin/c++ c++ /usr/bin/g++-9 --slave /usr/bin/g++ g++ /usr/bin/g++-9 \
        git submodule update --init --recursive
        git submodule update --remote
        cmake -B./lib/Catch2/build -H./lib/Catch2/ -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX=./catch_install
        cd lib/Catch2/build
        make install
        cd ../../..
        cmake -B./lib/fmt/build -H./lib/fmt -DFMT_TEST=OFF
        cd lib/fmt/build
        make -j8
        cd ../../..
        cmake -B./build -H. -Dfmt_DIR=./lib/fmt/build -DCatch2_DIR=./catch_install/lib/cmake/Catch2
        cd build
        make -j8
        make test
