name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Build and run tests
      run: |
        sudo add-apt-repository ppa:jonathonf/gcc-9.0
        sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
        sudo apt update
        sudo apt install -y gcc-9
        git submodule update --init --recursive
        git submodule update --remote
        export CXX=/usr/bin/clang++-9
        export CC=/usr/bin/clang-9
        cmake -B./lib/Catch2/build -H./lib/Catch2/ -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX=./catch_install
        cd lib/Catch2/build
        make install
        cd ../../..
        cmake -B./lib/fmt/build -H./lib/fmt -DFMT_TEST=OFF
        cd lib/fmt/build
        make -j8
        cd ../../..
        cmake -B./build -H. -Dfmt_DIR=./lib/fmt/build -DCatch2_DIR=./catch_install/lib/cmake/Catch2
        cd build
        make -j8
        make test
