name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Build and run tests
      run: |
        curl -SL http://releases.llvm.org/9.0.0/clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz | tar -xJC .
        sudo cp -r clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-18.04/ /usr/local/clang-9.0.0
        export LD_LIBRARY_PATH=/usr/local/clang-9.0.0/lib:$LD_LIBRARY_PATH
        export PATH=/usr/local/clang-9.0.0/bin:$PATH
        sudo ldconfig
        git submodule update --init --recursive
        git submodule update --remote
        export CC=/usr/bin/clang
        export CXX=/usr/bin/clang++
        cmake -B./lib/Catch2/build -H./lib/Catch2/ -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX=./catch_install
        cd lib/Catch2/build
        make install
        cd ../../..
        cmake -B./lib/fmt/build -H./lib/fmt -DFMT_TEST=OFF
        cd lib/fmt/build
        make -j8
        cd ../../..
        cmake -B./build -H. -Dfmt_DIR=./lib/fmt/build -DCatch2_DIR=./catch_install/lib/cmake/Catch2
        cd build
        make -j8
        make test
