name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Build and run tests
      run: |
        sudo add-apt-repository ppa:jonathonf/gcc-9.0
        sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
        sudo apt update
        sudo apt install -y gcc-9 g++-9
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 10
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 10
        sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 30
        sudo update-alternatives --set cc /usr/bin/gcc
        sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30
        sudo update-alternatives --set c++ /usr/bin/g++
        git clone https://github.com/sstephenson/bats.git
        cd bats
        sudo ./install.sh /usr/local
        cd ..
        git submodule update --init --recursive
        git submodule update --remote
        cmake -B./lib/Catch2/build -H./lib/Catch2/ -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX=./catch_install
        cd lib/Catch2/build
        make install
        cd ../../..
        cmake -B./lib/fmt/build -H./lib/fmt -DFMT_TEST=OFF
        cd lib/fmt/build
        make -j8
        cd ../../..
        cmake -B./lib/json/build -H./lib/json/ -DBUILD_TESTING=OFF
        cd lib/json/build
        make -j8
        cd ../../..

        cmake -B./build -H. -Dnlohmann_json_DIR=./lib/json/build -Dfmt_DIR=./lib/fmt/build -DCatch2_DIR=./catch_install/lib/cmake/Catch2
        cd build
        export CXX=/usr/bin/clang++
        export CC=/usr/bin/clang
        make -j8
        make test
        cd ../test/integration
        bash run_all.sh
