name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and run tests
      run: |
        git submodule update --init --recursive
        mkdir lib/Catch2/build
        cmake ..
        make
        cd ../../..
        mkdir build
        cd build
        cmake ..
        make
        make test
